# Generated by Django 4.0.6 on 2022-11-29 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_deliverystation_latitude_deliverystation_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('books', 'Books'), ('documents', 'Documents'), ('clothings', 'Clothings'), ('digital_products', 'Digital Products'), ('food', 'Food'), ('liquids', 'Liquids'), ('others', 'Others')], max_length=200)),
                ('deliverRequestedTime', models.DateTimeField()),
                ('delivered', models.BooleanField(default=False)),
                ('timeOfRequest', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Deliveries',
                'verbose_name_plural': 'Deliveries',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_station', to='core.deliverystation'),
        ),
        migrations.AlterField(
            model_name='place',
            name='displayName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ProductDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentTime', models.DateTimeField()),
                ('delivered', models.BooleanField(default=False)),
                ('currentLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_location', to='delivery.place')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='delivery.delivery')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_manager', to='core.deliverymanager')),
            ],
            options={
                'verbose_name': 'Product Deliveries',
                'verbose_name_plural': 'Product Deliveries',
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='deliveryPoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toPoint', to='delivery.place'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickupPoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromPoint', to='delivery.place'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_delivery', to=settings.AUTH_USER_MODEL),
        ),
    ]
