# Generated by Django 4.0.6 on 2022-11-28 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeName', models.CharField(max_length=250)),
                ('region', models.CharField(max_length=250)),
                ('town', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('dateCreated', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Delivery Stations',
                'verbose_name_plural': 'Delivery Stations',
            },
        ),
        migrations.CreateModel(
            name='DeliveryManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('joinedDate', models.DateField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station', to='core.deliverystation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Managers',
                'verbose_name_plural': 'Delivery Managers',
            },
        ),
    ]
